# hope this works
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/vidchops
hooks:
  deploy:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
  deploy-fe:
    - location: deploy-fe.sh
      timeout: 300
      runas: ubuntu